namespace: openafs_contrib
name: openafs
version: 1.9.4
readme: README.md
authors:
  - Cheyenne Wills <cwills@sinenomine.net>
  - Marc 'risson' Schmitt <marc.schmitt@risson.space>
  - Mark Vitale <mvitale@sinenomine.net>
  - Michael Meffie <mmeffie@sinenomine.net>
  - Ralf Brunckhorst <rbrunckhorst@sinenomine.net>
description: Playbooks, roles, and modules to deploy the OpenAFS distributed filesystem.
license: BSD-2-Clause
tags:
  - openafs
  - system
  - development
build_ignore:
  - 'builds'
  - 'docs'
  - 'extensions'
  - 'roles/*/molecule'
  - 'tests'
  - 'tox.ini'
  - '.ansible'
  - '.config'
  - '.envrc'
  - '.git'
  - '.gitignore'
  - '.readthedocs.yaml'
  - '.tox'
  - '.venv'
  - '.vscode'
  - '.pytest_cache'
  - '*/.ansible'
repository: 'https://github.com/openafs-contrib/ansible-openafs'
documentation: 'https://openafs-ansible-collection.readthedocs.io'
homepage: 'https://github.com/openafs-contrib/ansible-openafs'
issues: 'https://github.com/openafs-contrib/ansible-openafs/issues'
