---
dependency:
  name: galaxy
platforms:
  - name: m-playbook-default${AFS_TESTID}
    box: "${AFS_IMAGE:-generic/centos7}"
    groups:
      - afs_admin_client
      - afs_clients
      - afs_databases
      - afs_fileservers
      - afs_kdcs
provisioner:
  name: ansible
  env:
    ANSIBLE_PIPELINING: "True"
    ANSIBLE_STDOUT_CALLBACK: "yaml"
  inventory:
    group_vars:
      all:
        afs_realm: "${AFS_REALM:-EXAMPLE.COM}"
        afs_cell: "${AFS_CELL:-example.com}"
        afs_builds: "${AFS_BUILDS:-~/.cache/ansible-openafs/builds}"
        afs_git_repo: "${AFS_GIT_REPO:-git://git.openafs.org/openafs.git}"
        afs_git_version: "${AFS_GIT_VERSION:-master}"
        afs_install_archive: "${AFS_INSTALL_ARCHIVE}"
        afs_install_method: "${AFS_INSTALL_METHOD}"
        afs_module_install_method: "${AFS_MODULE_INSTALL_METHOD:-dkms}"
        afs_cell_files: "${MOLECULE_EPHEMERAL_DIRECTORY}"
        afs_csdb_file: "${MOLECULE_EPHEMERAL_DIRECTORY}/csdb.yaml"
        afs_pseudo_partitions: ['a', 'b']
        afs_git_repo: "${AFS_GIT_REPO:-git://git.openafs.org/openafs.git}"
        afs_git_version: "${AFS_GIT_VERSION:-master}"
        afs_always_build: "${AFS_ALWAYS_BUILD:-no}"
        afs_clean_build: "${AFS_CLEAN_BUILD:-yes}"
        # afs_afsd_opts: "-debug -dynroot -fakestat -afsdb"
        # afs_bosserver_opts: ""
verifier:
  name: ansible
scenario:
  create_sequence:
    - create
    - prepare
  check_sequence:
    - cleanup
    - destroy
    - create
    - prepare
    - converge
    - check
    - destroy
  converge_sequence:
    - create
    - prepare
    - converge
  destroy_sequence:
    - cleanup
    - destroy
  test_sequence:
    - cleanup
    - destroy
    - create
    - prepare
    - converge
    - verify
    - cleanup
    - destroy
