---
- name: Add OpenAFS yum repo
  yum_repository:
    name: openafs
    description: OpenAFS yum repo
    baseurl: "{{ afs_openafs_client_repourl }}"
    gpgcheck: no

- name: Install OpenAFS base packages
  yum:
    state: present
    name:
      - openafs
      - openafs-krb5

- name: Query installed OpenAFS version
  shell: rpm -q --queryformat "%{VERSION}" openafs
  args:
    warn: False
  register: rpm_query
  changed_when: False

- name: Set kernel module package version
  set_fact:
    afs_openafs_kmod_version: "{{ rpm_query.stdout }}"
    afs_openafs_kmod_release: "{{ afs_openafs_kmod_prefix }}.{{ ansible_kernel | regex_replace('-','_') }}"

- name: Add epel yum repo
  become: yes
  yum:
    name: epel-release
    state: present
    update_cache: yes
  when: afs_client_install_dkms|bool

# Note: Workaround missing "requires" in the dkms-openafs package.
- name: Install OpenAFS DKMS requirements
  yum:
    state: present
    name:
      - make
      - "kernel-devel-{{ ansible_kernel }}"
  when: afs_client_install_dkms|bool

- name: Install OpenAFS client with DKMS
  yum:
    state: present
    name:
      - openafs-client
      - kernel-devel
      - dkms-openafs
  when: afs_client_install_dkms|bool

- name: Install OpenAFS client
  yum:
    state: present
    name:
      - openafs-client
      - kmod-openafs-{{ afs_openafs_kmod_version }}-{{ afs_openafs_kmod_release }}
  when: not afs_client_install_dkms|bool

- name: Set client startup options
  lineinfile:
    path: /etc/sysconfig/openafs
    regexp: "^AFSD_ARGS="
    line: 'AFSD_ARGS="{{ afs_afsd_opts }}"'
    state: present
  notify:
    - Restart OpenAFS client
