---
- name: "Debian: Install build essentials"
  apt:
    state: present
    name: "build-essential"
    update_cache: yes

- name: "Debian: Install kernel headers"
  apt:
    state: present
    name: "linux-headers-{{ ansible_kernel }}"

- name: "Debian: Build OpenAFS kernel module"
  apt:
    state: present
    name: openafs-modules-dkms

- name: "Debian: Get kernel modules"
  command: lsmod
  check_mode: no
  changed_when: false
  register: lsmod_results

- name: "Debian: Trace lsmod output"
  debug:
    var: lsmod_results
    verbosity: 1

- name: "Debian: Load openafs kernel module"
  command: modprobe openafs
  when: not lsmod_results.stdout is search('openafs')

- name: "Debian: Get kernel modules"
  command: lsmod
  check_mode: no
  changed_when: false
  register: lsmod_results

- name: "Debian: Verify the OpenAFS kernel module is loaded"
  assert:
    that:
      lsmod_results.stdout is search('openafs')

- name: "Debian: Prevent openafs client service until configured"
  copy:
    src: "Debian/policy-rc.d"
    dest: "/usr/sbin/policy-rc.d"
    mode: "0755"
    backup: yes

- name: "Debian: Install OpenAFS client"
  apt:
    state: present
    install_recommends: no
    name:
      - openafs-client
      - openafs-krb5

- name: "Debian: Restore service policy"
  file:
    path: "/usr/sbin/policy-rc.d"
    state: absent
