---
dependency:
  name: galaxy
driver:
  name: molecule-proxmox
  options:
    node: "${PROXMOX_NODE}"
    proxmox_secrets: "${PROXMOX_SECRETS_FILE}"
    ssh_user: "${PROXMOX_SSH_USER}"
    ssh_identity_file: "${PROXMOX_SSH_IDENTITY_FILE}"
    template_name: "${PROXMOX_TEMPLATE_NAME:-alma9}"
platforms:
  - name: m-role-server${AFS_TESTID}
    groups:
      - afs_databases
      - afs_fileservers
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        afs_cell: "example.com"
        afs_cell_files: "${MOLECULE_EPHEMERAL_DIRECTORY}"
        afs_install_method: "bdist"
        # afs_security_model: "${AFS_SECURITY_MODEL:-none}"
        afs_csdb_file: "${MOLECULE_EPHEMERAL_DIRECTORY}/csdb.yaml"
        afs_pseudo_partitions: ['a', 'b']
        afs_service_keytab: "../__files__/example-aes.keytab"
        afs_install_archive: "${AFS_INSTALL_ARCHIVE}"
verifier:
  name: ansible
scenario:
  create_sequence:
    - create
    - prepare
  check_sequence:
    - cleanup
    - destroy
    - create
    - prepare
    - converge
    - check
    - destroy
  converge_sequence:
    - create
    - prepare
    - converge
  destroy_sequence:
    - cleanup
    - destroy
  test_sequence:
    - cleanup
    - destroy
    - create
    - prepare
    - converge
    - verify
    - cleanup
    - destroy
